    <div class="container">
        <h2>Adicionar Cliente</h2>
        <form action="/salvarCliente" method="post">
        	<input type="hidden" class="form-control" id="Id" placeholder="Digite a id" name="id" value="0">
            
            <div class="form-group">
                <label for="nome">Nome:</label>
                <input type="text" class="form-control" id="nome" placeholder="Digite o nome do Cliente" name="nome">
            </div>
           <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
