<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agendamento de Serviços</title>
    <link rel="icon" href="../img/Imagem1.png">
</head>

<body>
    <br>

    <header>
        <img src="../img/logo.png" alt="heicao" width="300px">
        <ul>
            <a href="login.html">
                <li>Login</li>
            </a>
            <a href="tela_servicos.php">
                <li>Serviços</li>
            </a>
            <a href="#">
                <li>Sobre</li>
            </a>
            <a href="#">
                <li>Contato</li>
            </a>
        </ul>
    </header>

    <style>
        body {
            font-family: 'League Spartan', sans-serif;
            margin-left: auto;
            margin-right: auto;
            background-image: url("../img/teste.png");
            background-repeat: no-repeat;
            background-size: cover;
            background-color: #0C4271;

        }

        .principal {
            width: 700px;
            height: 480px;
            align-items: center;
            justify-content: center;
            text-align: center;
            border: 7px solid rgb(236, 233, 233);
            border-radius: 30px;
            margin: auto;

        }

        header {
            align-items: center;
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            padding-left: 10px;

        }

        a {
            color: rgb(112, 111, 111);
            font-weight: bold;
            font-size: 20px;
        }

        a:hover {
            color: rgb(202, 86, 223);
            font-weight: bold;
            transition: 0.3s all;
        }

        li {
            display: inline-block;
            margin: 20px;
        }


        input {
            height: 10px;
            padding: 15px;
            border-radius: 9px;
            font-size: 15px;
            color: rgb(202, 86, 223);
        }

        .titulo {
            color: rgb(202, 86, 223);
            font-size: 40px;
            font-weight: bold;
            align-items: center;
            justify-content: center;

        }


        form [type="submit"] {
            height: 45px;
            width: 150px;
            background-color: rgb(202, 86, 223);
            color: white;
            font-weight: bold;
            border: 9px;
            cursor: pointer;
            font-size: 20;
        }

        form [type="submit"]:hover {
            background-color: white;
            transition: 0.3s all;
            color: rgb(202, 86, 223);
            border: 3px solid rgb(202, 86, 223);
            border-radius: 9px;


        }

        .link {
            color: #0C4271;
        }

        .menu {
            height: 35px;
            width: 150px;
            border-radius: 9px;
            border: 2px solid black;

        }
    </style>

    <br><br><br><br><br><br>
    <div class="principal">
        <h1 class="titulo"> Agendamento </h1>
        Preencha as informações abaixo<br><br>
        <form action="tela_agendamento.php" method="post">
            <br>
            <table style="width:100%">
                <tr>
                    <td>
                        <p>
                            <b>Serviço:</b><br><br>
                            <select size="1" class="menu" id="menu_servicos">
                                <option id="selected"></option>
                                <option value>Banho e Tosa</option>
                                <option value>Day Care</option>
                                <option value>Dog Walker</option>
                                <option value>Pet Sitter</option>
                                <option value>Consulta Veterinária</option>
                                <option value>Hospedagem</option>
                            </select>
                        </p>
                    </td>
                    <td>
                        <p>
                            <b>Pet:</b><br><br>
                            <select size="1" class="menu" id="menu_pet">
                                <option value></option> /*deixar essa em branco*
                                <option value="lulu">lulu</option>
                            </select>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>
                            <b>Dia:</b><br><br>
                            <select size="1" class="menu" id="menu_dia">
                                <option value></option> /*deixar essa em branco*
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                                <option value="11">11</option>
                                <option value="12">12</option>
                                <option value="13">13</option>
                                <option value="14">14</option>
                                <option value="15">15</option>
                                <option value="16">16</option>
                                <option value="17">17</option>
                                <option value="18">18</option>
                                <option value="19">19</option>
                                <option value="20">20</option>
                                <option value="21">21</option>
                                <option value="22">22</option>
                                <option value="23">23</option>
                                <option value="24">24</option>
                                <option value="25">25</option>
                                <option value="26">26</option>
                                <option value="27">27</option>
                                <option value="28">28</option>
                                <option value="29">29</option>
                                <option value="30">30</option>
                                <option value="31">31</option>
                            </select>
                        </p>
                    </td>
                    <td>
                        <p>
                            <b>Horário:</b><br><br>
                            <select size="1" class="menu" id="menu_horario">
                                <option value></option>
                                <option value="10:30">10:30</option>
                                <option value="11:00">11:00</option>
                                <option value="11:30">11:30</option>
                                <option value="12:00">12:00</option>
                                <option value="13:00">13:00</option>
                                <option value="13:30">13:30</option>
                                <option value="14:00">14:00</option>
                                <option value="14:30">14:30</option>
                                <option value="15:00">15:00</option>
                                <option value="15:30">15:30</option>
                                <option value="16:00">16:00</option>
                                <option value="16:30">16:30</option>
                                <option value="17:00">17:00</option>
                                <option value="17:30">17:30</option>
                            </select>
                        </p>
                    </td>
                </tr>

            </table>
            <p><br>
                <input type="submit" value="Agendar">
            </p>
    </div>
</body>
</html>