<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agendamento</title>
</head>

<body>
    <br>

    <header>
        <img src="../img/logo.png" alt="heicao" width="300px">
        <ul>
            <a href="login.html">
                <li>Login</li>
              </a>
              <a href="tela_servicos.php">
                <li>Serviços</li>
              </a>
            <a href="#">
                <li>Sobre</li>
            </a>
            <a href="#">
                <li>Contato</li>
            </a>
        </ul>
    </header>

    <style>
        body {
            font-family: 'League Spartan', sans-serif;
            margin-left: auto;
            margin-right: auto;
            background-image: url("../img/teste.png");
            background-repeat: no-repeat;
            background-size: cover;
            background-color: #0C4271;

        }

        .principal {
            width: 700px;
            height: 500px;
            align-items: center;
            justify-content: center;
            text-align: center;
            border: 7px solid rgb(236, 233, 233);
            border-radius: 30px;
            margin: auto;

        }

        header {
            align-items: center;
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            padding-left: 10px;

        }

        a {
            color: rgb(112, 111, 111);
            font-weight: bold;
            font-size: 20px;
        }

        a:hover {
            color: rgb(202, 86, 223);
            font-weight: bold;
            transition: 0.3s all;
        }

        li {
            display: inline-block;
            margin: 20px;
        }


        input {
            height: 10px;
            padding: 15px;
            border-radius: 9px;
            font-size: 15px;
            color: rgb(202, 86, 223);
        }

        .titulo {
            color: rgb(202, 86, 223);
            font-size: 40px;
            font-weight: bold;
            align-items: center;
            justify-content: center;

        }


        form [type="submit"] {
            height: 45px;
            width: 150px;
            background-color: rgb(202, 86, 223);
            color: white;
            font-weight: bold;
            border: 9px;
            cursor: pointer;
            font-size: 20;
        }

        form [type="submit"]:hover {
            background-color: white;
            transition: 0.3s all;
            color: rgb(202, 86, 223);
            border: 3px solid rgb(202, 86, 223);
            border-radius: 9px;


        }

        .link {
            color: #0C4271;
        }

        .menu {
            height: 35px;
            width: 150px;
            border-radius: 9px;
            border: 2px solid black;

        }
        
    </style>

    <br><br><br><br><br><br>
    <div class="principal">
        <h1 class="titulo"> Agendamento </h1>
        Preencha as informações abaixo<br>
        <form action="tela_agendamento.php" method="post">
            <br>
            <table style="width:100%">
                <tr>
                    <td>
                        <p>
                            <b>Serviço:</b><br><br>
                            <select size="1" class="menu" id="menu_servicos">
                                <option id="selected"></option>
                                <option value>Banho e Tosa</option>
                                <option value>Day Care</option>
                                <option value>Dog Walker</option>
                                <option value>Pet Sitter</option>
                                <option value>Consulta Veterinária</option>
                                <option value>Hospedagem</option>
                            </select>
                        </p>
                    </td>
                    <td>
                        <p>
                            <b>Pet:</b><br><br>
                            <select size="1" class="menu" id="menu_pet">
                                <option value></option>
                                <option value>a</option>
                                <option value>b</option>
                                <option value>c</option>
                            </select>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>
                            <b>Dia:</b><br><br>
                            <select size="1" class="menu" id="menu_dia">
                                <option value></option>
                                <option value>a</option>
                                <option value>b</option>
                                <option value>c</option>
                            </select>
                        </p>
                    </td>
                    <td>
                        <p>
                            <b>Horário:</b><br><br>
                            <select size="1" class="menu" id="menu_horario">
                                <option value></option>
                                <option value>a</option>
                                <option value>b</option>
                                <option value>c</option>
                            </select>
                        </p>
                    </td>
                </tr>

            </table>
            <p><br>
                <input type="submit" value="Agendar">
            </p>
    </div>


</body>

</html>